/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formularios;

import dialogsAgente.DlgRegistrarAgente;
import dialogsCasting.DlgBuscarCasting;
import dialogsCasting.DlgRegistrarCasting;
import dialogsCliente.DlgRegistrarCliente;
import entidades.Cliente;
import interfaces.*;
import java.util.List;
import dlgcompartidos.DlgLlenarPerfil;
import entidades.Agente;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import negocio.PersistenciaFachada;
import utils.Conversiones;

public class CastingForm extends javax.swing.JFrame {

    Conversiones conversiones;
    IPersistenciaFachada persistencia;
    ArrayList perfiles;

    List<Cliente> clientes;
    List<Agente> agentes;

    public CastingForm() {
        persistencia = PersistenciaFachada.getInstance();
        conversiones = Conversiones.getInstance();
        perfiles = new ArrayList<>();
        initComponents();
        setLocationRelativeTo(null);
        setVisible(true);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CastingForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CastingForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CastingForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CastingForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CastingForm().setVisible(true);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        opcionMenuAgregarCasting = new javax.swing.JMenuItem();
        opcionMenuBuscarCasting = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        opcionMenuAgregarCliente = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        opcionMenuAgregarAgente = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Proyecto Casting");

        jMenu1.setText("Casting");

        opcionMenuAgregarCasting.setText("Registrar Casting");
        opcionMenuAgregarCasting.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcionMenuAgregarCastingActionPerformed(evt);
            }
        });
        jMenu1.add(opcionMenuAgregarCasting);

        opcionMenuBuscarCasting.setText("Buscar Casting");
        opcionMenuBuscarCasting.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcionMenuBuscarCastingActionPerformed(evt);
            }
        });
        jMenu1.add(opcionMenuBuscarCasting);

        jMenuItem1.setText("Registrar Perfil");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Cliente");

        opcionMenuAgregarCliente.setText("Registrar Cliente");
        opcionMenuAgregarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcionMenuAgregarClienteActionPerformed(evt);
            }
        });
        jMenu2.add(opcionMenuAgregarCliente);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Agente");

        opcionMenuAgregarAgente.setText("Registrar Agente");
        opcionMenuAgregarAgente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcionMenuAgregarAgenteActionPerformed(evt);
            }
        });
        jMenu3.add(opcionMenuAgregarAgente);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 498, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 431, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void opcionMenuAgregarCastingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcionMenuAgregarCastingActionPerformed
        DefaultComboBoxModel clientes = conversiones.clientesComboBoxModel(persistencia.buscarClientes());
        DefaultComboBoxModel agentes = conversiones.agentesComboBoxModel(persistencia.buscarAgentes());
        
        if(clientes != null && agentes!= null) new DlgRegistrarCasting(clientes, agentes);
        else JOptionPane.showMessageDialog(null, "Necesita agregar minimo un cliente o agente para agregar un Casting!",
                    "Casting", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_opcionMenuAgregarCastingActionPerformed

    private void opcionMenuAgregarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcionMenuAgregarClienteActionPerformed
        new DlgRegistrarCliente();
    }//GEN-LAST:event_opcionMenuAgregarClienteActionPerformed

    private void opcionMenuAgregarAgenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcionMenuAgregarAgenteActionPerformed
        new DlgRegistrarAgente();
    }//GEN-LAST:event_opcionMenuAgregarAgenteActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        DefaultComboBoxModel castings = conversiones.castingsComboBoxModel(persistencia.buscarCastings());
        if (castings == null) {
            JOptionPane.showMessageDialog(null, "Necesita agregar un casting para agregarle un Perfil!",
                    "Perfil", JOptionPane.INFORMATION_MESSAGE);
        } else {
            new DlgLlenarPerfil(perfiles, castings);
        }

    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void opcionMenuBuscarCastingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcionMenuBuscarCastingActionPerformed
        new DlgBuscarCasting();
    }//GEN-LAST:event_opcionMenuBuscarCastingActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem opcionMenuAgregarAgente;
    private javax.swing.JMenuItem opcionMenuAgregarCasting;
    private javax.swing.JMenuItem opcionMenuAgregarCliente;
    private javax.swing.JMenuItem opcionMenuBuscarCasting;
    // End of variables declaration//GEN-END:variables
}
