/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dialogsCasting;

import dlgcompartidos.DlgDireccion;
import entidades.CastingOnline;
import entidades.CastingPresencial;
import entidades.Direccion;
import entidades.Sala;
import javax.swing.JOptionPane;
import javax.swing.SpinnerNumberModel;

/**
 *
 * @author Sammy Guergachi <sguergachi at gmail.com>
 */
public class DlgSeleccionarModalidad extends javax.swing.JDialog {

    Direccion direccion = new Direccion();
    DlgDireccion dlgDireccion;
    static CastingPresencial castingPresencial;
    static CastingOnline castingOnline;
    int operacion;

    /**
     * Creates new form SeleccionarModalidad
     */
    public DlgSeleccionarModalidad(CastingPresencial cp, CastingOnline co) {
        initComponents();
        this.castingPresencial = cp;
        this.castingOnline = co;
        operacion = 0;
        llenarCampos();
        setLocationRelativeTo(null);
        setVisible(true);
    }
    
    public DlgSeleccionarModalidad(CastingPresencial cp, CastingOnline co, int operacion) {
        initComponents();
        this.castingPresencial = cp;
        this.castingOnline = co;
        this.operacion = 1;
        llenarCampos();
        setLocationRelativeTo(null);
        setVisible(true);
        desactivarCampos();
    }
    
    private void desactivarCampos(){
        comboBoxModalidad.setEnabled(false);
        spinnerNumPersonasOnline.setEnabled(false);
        txtNombreSala.setEditable(false);
        txtDescripcionSala.setEditable(false);
        spinnerNumPersonasOnline.setEnabled(false);
        txtOnlineEnlace.setEditable(false);
        btnGuardar.setEnabled(false);
        btnLimpiar.setEnabled(false);
        btnCancelar.setText("Salir");
    }
    
    private void llenarCampos() {
        SpinnerNumberModel modeloSpinnerPresencial = new SpinnerNumberModel();
        SpinnerNumberModel modeloSpinnerOnline = new SpinnerNumberModel();
        modeloSpinnerPresencial.setMaximum(Integer.MAX_VALUE);
        modeloSpinnerPresencial.setMinimum(1);
        modeloSpinnerOnline.setMaximum(Integer.MAX_VALUE);
        modeloSpinnerOnline.setMinimum(1);

        spinnerNumPersonasOnline.setEnabled(false);
        txtOnlineEnlace.setEnabled(false);

        spinnerNumPersonasOnline.setModel(modeloSpinnerOnline);
        spinnerNumPersonasOnline.setValue(1);
        
        spinnerNumPersonasPresencial.setModel(modeloSpinnerPresencial);
        spinnerNumPersonasPresencial.setValue(1);
        

        if (castingPresencial.getSala() != null) {
            spinnerNumPersonasPresencial.setValue(castingPresencial.getNumPersonas());
            direccion = castingPresencial.getSala().getDireccion();
            txtNombreSala.setText(castingPresencial.getSala().getNombre());
            txtDescripcionSala.setText(castingPresencial.getSala().getDescripcion());
        } else if (castingOnline.getAsistente() != 0) {
            comboBoxModalidad.setSelectedIndex(1);
            spinnerNumPersonasOnline.setValue(castingOnline.getAsistente());
            txtOnlineEnlace.setText(castingOnline.getEnlace());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        comboBoxModalidad = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        spinnerNumPersonasPresencial = new javax.swing.JSpinner();
        lblPresencial = new javax.swing.JLabel();
        btnRegistrarDireccion = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtNombreSala = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescripcionSala = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        lblOnline = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtOnlineEnlace = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        spinnerNumPersonasOnline = new javax.swing.JSpinner();
        btnGuardar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Registrar Modalidad");
        setBackground(new java.awt.Color(0, 0, 0));

        comboBoxModalidad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Presencial", "Online" }));
        comboBoxModalidad.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboBoxModalidadItemStateChanged(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("Modalidad:");

        jLabel2.setText("Número de Personas:");

        spinnerNumPersonasPresencial.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                spinnerNumPersonasPresencialInputMethodTextChanged(evt);
            }
        });

        lblPresencial.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblPresencial.setText("Presencial");

        btnRegistrarDireccion.setText("Registrar Dirección Sala");
        btnRegistrarDireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarDireccionActionPerformed(evt);
            }
        });

        jLabel4.setText("Nombre Sala:");

        jLabel5.setText("Descripción Sala:");

        txtDescripcionSala.setColumns(20);
        txtDescripcionSala.setRows(5);
        jScrollPane1.setViewportView(txtDescripcionSala);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNombreSala, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPresencial)
                            .addComponent(spinnerNumPersonasPresencial, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addComponent(btnRegistrarDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(lblPresencial)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spinnerNumPersonasPresencial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRegistrarDireccion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtNombreSala, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addContainerGap())
        );

        lblOnline.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblOnline.setText("Online");
        lblOnline.setEnabled(false);

        jLabel14.setText("Enlace:");

        jLabel15.setText("Número de Personas:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel15)
                    .addComponent(jLabel14))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 10, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(spinnerNumPersonasOnline, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(77, 77, 77))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(lblOnline)
                                .addGap(187, 187, 187))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txtOnlineEnlace)
                        .addContainerGap())))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(lblOnline)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(spinnerNumPersonasOnline, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtOnlineEnlace, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(96, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(68, 68, 68))
            .addGroup(layout.createSequentialGroup()
                .addGap(235, 235, 235)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(comboBoxModalidad, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77)
                .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(comboBoxModalidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar)
                    .addComponent(btnLimpiar)
                    .addComponent(btnCancelar))
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void comboBoxModalidadItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboBoxModalidadItemStateChanged
        if (comboBoxModalidad.getSelectedIndex() == 0) {
            spinnerNumPersonasPresencial.setEnabled(true);
            btnRegistrarDireccion.setEnabled(true);
            txtNombreSala.setEnabled(true);
            txtDescripcionSala.setEnabled(true);
            lblPresencial.setEnabled(true);
            spinnerNumPersonasOnline.setEnabled(false);
            txtOnlineEnlace.setEnabled(false);
            lblOnline.setEnabled(false);
            txtOnlineEnlace.setEnabled(false);
        } else {
            spinnerNumPersonasOnline.setEnabled(true);
            txtOnlineEnlace.setEnabled(true);
            lblOnline.setEnabled(true);
            txtOnlineEnlace.setEnabled(true);
            spinnerNumPersonasPresencial.setEnabled(false);
            btnRegistrarDireccion.setEnabled(false);
            txtNombreSala.setEnabled(false);
            txtDescripcionSala.setEnabled(false);
            lblPresencial.setEnabled(false);

        }
    }//GEN-LAST:event_comboBoxModalidadItemStateChanged

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        limpiar();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnRegistrarDireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarDireccionActionPerformed

        dlgDireccion = new DlgDireccion(direccion,operacion);

    }//GEN-LAST:event_btnRegistrarDireccionActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed

        if (!validaciones()) {
            JOptionPane.showMessageDialog(null, "Campos vacíos o inválidos, verifiquelos e intentelo de nuevo",
                    "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (comboBoxModalidad.getSelectedIndex() == 0) {
            int numPersonas = (int) spinnerNumPersonasPresencial.getValue();
            String descripcion = txtDescripcionSala.getText();
            String nombre = txtNombreSala.getText();
            Sala sala = new Sala(nombre, direccion, descripcion);
            castingPresencial = new CastingPresencial(numPersonas, sala);
            castingOnline = new CastingOnline();
            JOptionPane.showMessageDialog(null, "Casting Presencial registrado correctamente",
                        "Modalidad", JOptionPane.INFORMATION_MESSAGE);
        } else {
            int numPersonas = (int) spinnerNumPersonasOnline.getValue();
            String enlace = txtOnlineEnlace.getText();
            castingOnline = new CastingOnline(enlace, numPersonas);
            castingPresencial = new CastingPresencial();
            JOptionPane.showMessageDialog(null, "Casting Online registrado correctamente",
                        "Modalidad", JOptionPane.INFORMATION_MESSAGE);
            
        }
        
        dispose();
    }//GEN-LAST:event_btnGuardarActionPerformed

    public static CastingPresencial getCastingPresencial() {
        if (castingPresencial == null) {
            return new CastingPresencial();
        }
        return castingPresencial;

    }

    public static CastingOnline getCastingOnline() {
        if (castingOnline == null) {
            return new CastingOnline();
        }
        return castingOnline;
    }

    private void spinnerNumPersonasPresencialInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_spinnerNumPersonasPresencialInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_spinnerNumPersonasPresencialInputMethodTextChanged

    private boolean validaciones() {

        if (comboBoxModalidad.getSelectedIndex() == 0) {
            String nombreSala = txtNombreSala.getText();
            String descripcionSala = txtDescripcionSala.getText();
            try {
                int numPersonas = (int) spinnerNumPersonasPresencial.getValue();
            } catch (NumberFormatException e) {
                return false;
            }
            try {
                if (direccion == null && direccion.getCalle().equals("")) return false;
            } catch (NullPointerException e) {
                return false;
            }

            if (nombreSala.equals("") || descripcionSala.equals("")) {
                return false;
            }
        } else {
            try {
                int numPersonas = (int) spinnerNumPersonasOnline.getValue();
            } catch (NumberFormatException e) {
                return false;
            }

            String enlace = txtOnlineEnlace.getText();
            return !enlace.equals("");
        }
        return true;
    }

    public void limpiar() {
        spinnerNumPersonasOnline.setValue(1);
        spinnerNumPersonasPresencial.setValue(1);
        txtNombreSala.setText("");
        txtDescripcionSala.setText("");
        comboBoxModalidad.setSelectedIndex(0);
        txtOnlineEnlace.setText("");
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnRegistrarDireccion;
    private javax.swing.JComboBox<String> comboBoxModalidad;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblOnline;
    private javax.swing.JLabel lblPresencial;
    private javax.swing.JSpinner spinnerNumPersonasOnline;
    private javax.swing.JSpinner spinnerNumPersonasPresencial;
    private javax.swing.JTextArea txtDescripcionSala;
    private javax.swing.JTextField txtNombreSala;
    private javax.swing.JTextField txtOnlineEnlace;
    // End of variables declaration//GEN-END:variables
}
