/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dlgcompartidos;

import Enums.Estado;
import Enums.Sexo;
import entidades.Perfil;
import Enums.EPerfil;
import java.awt.HeadlessException;
import java.awt.event.KeyEvent;
import java.text.DecimalFormat;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Sammy Guergachi <sguergachi at gmail.com>
 */
public class DlgLlenarPerfil extends javax.swing.JDialog {

    ArrayList<Perfil> perfiles;

    /**
     * Creates new form LlenarPerfil
     *
     * @param perfiles
     */
    public DlgLlenarPerfil(ArrayList<Perfil> perfiles) {
        initComponents();
        setLocationRelativeTo(null);
        setVisible(true);
        this.perfiles = perfiles;
        llenarTabla(perfiles);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        comboBoxEstados = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        comboBoxSexo = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        txtAlturaMin = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtAlturaMax = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtEdadMin = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtEdadMax = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtColorPelo = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtColorOjos = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        comboBoxPerfil = new javax.swing.JComboBox<>();
        comboBoxExperiencia = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        btnLimpiar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPerfil2 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblPerfil1 = new javax.swing.JTable();
        btnInsertar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Llenar Perfil");

        jLabel1.setText("Código:");

        txtCodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCodigoKeyTyped(evt);
            }
        });

        jLabel2.setText("Estado:");

        comboBoxEstados.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Aguascalientes", "Baja California", "Baja California Sur", "Campeche", "Coahuila", "Colima", "Chiapas", "Chihuahua", "Durango", "CDMX", "Guanajuato", "Guerrero", "Hidalgo", "Jalisco", "Michoacán", "Morelos", "Nayarit", "Nuevo León", "Oaxaca", "Puebla", "Querétaro", "Quintana Roo", "San Luis Potosí", "Sinaloa", "Sonora", "Tabasco", "Tamaulipas", "Tlaxcala", "Veracruz", "Yucatán", "Zacatecas" }));

        jLabel3.setText("Sexo:");

        comboBoxSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masculino", "Femenino" }));

        jLabel4.setText("Altura Min:");

        txtAlturaMin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAlturaMinKeyTyped(evt);
            }
        });

        jLabel5.setText("Altura Max:");

        txtAlturaMax.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAlturaMaxKeyTyped(evt);
            }
        });

        jLabel6.setText("Edad Min:");

        txtEdadMin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtEdadMinKeyTyped(evt);
            }
        });

        jLabel7.setText("Edad Max:");

        txtEdadMax.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtEdadMaxKeyTyped(evt);
            }
        });

        jLabel8.setText("Color de Pelo:");

        txtColorPelo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtColorPeloKeyTyped(evt);
            }
        });

        jLabel9.setText("Color de Ojos:");

        txtColorOjos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtColorOjosKeyTyped(evt);
            }
        });

        jLabel10.setText("Tipo de Perfil:");

        comboBoxPerfil.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Modelo", "Actor" }));

        comboBoxExperiencia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Si", "No" }));

        jLabel11.setText("Con experiencia:");

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        tblPerfil2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Edad Max", "Color Pelo", "Color Ojos", "Tipo Perfil", "Experiencia"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblPerfil2);

        tblPerfil1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Estado", "Sexo", "Altura Min", "Altura Max", "Edad Min"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Float.class, java.lang.Float.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblPerfil1);

        btnInsertar.setText("Insertar");
        btnInsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertarActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel11)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(btnLimpiar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnInsertar, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(65, 65, 65)
                        .addComponent(btnCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(comboBoxExperiencia, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtCodigo)
                            .addComponent(comboBoxEstados, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(comboBoxSexo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtAlturaMin)
                            .addComponent(txtAlturaMax)
                            .addComponent(txtEdadMin)
                            .addComponent(txtEdadMax)
                            .addComponent(txtColorPelo)
                            .addComponent(txtColorOjos)
                            .addComponent(comboBoxPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 555, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(15, 15, 15))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(340, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 553, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(16, 16, 16)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(comboBoxEstados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboBoxSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtAlturaMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(txtAlturaMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtEdadMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtEdadMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtColorPelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminar)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtColorOjos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(comboBoxPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboBoxExperiencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar)
                    .addComponent(btnLimpiar)
                    .addComponent(btnCancelar)
                    .addComponent(btnInsertar))
                .addContainerGap(10, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(48, 48, 48)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(393, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        limpiar();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        dispose();
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnInsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertarActionPerformed
        if (!validar()) {
            return;
        }

        String codigo = txtCodigo.getText();

        Estado estado = toEnum(comboBoxEstados.getSelectedItem().toString());

        Sexo sexo = toSexo(comboBoxSexo.getSelectedItem().toString());

        String stringAlturaMin = txtAlturaMin.getText();

        DecimalFormat df = new DecimalFormat("#.00");

        float alturaMin = Float.valueOf(stringAlturaMin);
        df.format(alturaMin);
        String stringAlturaMax = txtAlturaMax.getText();
        float alturaMax = Float.valueOf(stringAlturaMax);
        df.format(alturaMax);
        String stringEdadMin = txtEdadMin.getText();
        int edadMin = Integer.parseInt(stringEdadMin);

        String stringEdadMax = txtEdadMax.getText();
        int edadMax = Integer.parseInt(stringEdadMax);

        String colorCabello = txtColorPelo.getText();
        String colorOjos = txtColorOjos.getText();
        EPerfil tipoPerfil = toPerfil(comboBoxPerfil.getSelectedItem().toString());
        boolean experiencia = (comboBoxExperiencia.getSelectedItem().toString().equals("Si"));

        Perfil perfil = new Perfil(codigo, estado, sexo, alturaMax,
                alturaMin, edadMin, edadMax, colorCabello, colorOjos, experiencia, tipoPerfil);

        perfiles.add(perfil);

        llenarTabla(perfiles);
    }//GEN-LAST:event_btnInsertarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed

        DefaultTableModel modelPerfil1 = (DefaultTableModel) tblPerfil1.getModel();
        DefaultTableModel modelPerfil2 = (DefaultTableModel) tblPerfil2.getModel();
        try {
            if (tblPerfil1.getSelectedRow() != -1) {
                perfiles.remove(tblPerfil1.getSelectedRow());

                modelPerfil1.removeRow(tblPerfil1.getSelectedRow());
                modelPerfil2.removeRow(tblPerfil1.getSelectedRow());
            } else if (tblPerfil2.getSelectedRow() != -1) {
                perfiles.remove(tblPerfil2.getSelectedRow());

                modelPerfil1.removeRow(tblPerfil2.getSelectedRow());
                modelPerfil2.removeRow(tblPerfil2.getSelectedRow());
            } else {
                JOptionPane.showMessageDialog(null, "Seleccione un campo para eliminar.",
                        "Error", JOptionPane.ERROR_MESSAGE);
            }

        } catch (HeadlessException e) {
            JOptionPane.showMessageDialog(null, "Seleccione un campo para eliminar.",
                    "Error", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btnEliminarActionPerformed

    private void txtCodigoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigoKeyTyped
        int key = evt.getKeyChar();

        boolean numeros = key >= 48 && key <= 57;

        if (!numeros) {
            evt.consume();
        }

        if (txtCodigo.getText().trim().length() == 5) {
            evt.consume();
        }    }//GEN-LAST:event_txtCodigoKeyTyped

    private void txtEdadMinKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEdadMinKeyTyped
        int key = evt.getKeyChar();

        boolean numeros = key >= 48 && key <= 57;

        if (!numeros) {
            evt.consume();
        }

        if (txtEdadMin.getText().trim().length() == 3) {
            evt.consume();
        }
    }//GEN-LAST:event_txtEdadMinKeyTyped

    private void txtAlturaMinKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAlturaMinKeyTyped
        String alturaMin = txtAlturaMin.getText();

        int k = evt.getKeyChar();

        if (k >= 46 && k <= 57) {
            if (k == 46) {
                int tama = alturaMin.length();
                for (int i = 0; i <= tama; i++) {
                    if (alturaMin.contains(".")) {
                        evt.setKeyChar((char) KeyEvent.VK_CLEAR);
                    }
                }
            }
            if (k == 47) {
                evt.setKeyChar((char) KeyEvent.VK_CLEAR);
            }
        } else {
            evt.setKeyChar((char) KeyEvent.VK_CLEAR);
            evt.consume();
        }

    }//GEN-LAST:event_txtAlturaMinKeyTyped

    private void txtAlturaMaxKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAlturaMaxKeyTyped
        String alturaMax = txtAlturaMax.getText();

        int k = evt.getKeyChar();

        if (k >= 46 && k <= 57) {
            if (k == 46) {
                int tama = alturaMax.length();
                for (int i = 0; i <= tama; i++) {
                    if (alturaMax.contains(".")) {
                        evt.setKeyChar((char) KeyEvent.VK_CLEAR);
                    }
                }
            }
            if (k == 47) {
                evt.setKeyChar((char) KeyEvent.VK_CLEAR);
            }
        } else {
            evt.setKeyChar((char) KeyEvent.VK_CLEAR);
            evt.consume();
        }
    }//GEN-LAST:event_txtAlturaMaxKeyTyped

    private void txtEdadMaxKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEdadMaxKeyTyped
        int key = evt.getKeyChar();

        boolean numeros = key >= 48 && key <= 57;

        if (!numeros) {
            evt.consume();
        }

        if (txtEdadMax.getText().trim().length() == 10) {
            evt.consume();
        }
    }//GEN-LAST:event_txtEdadMaxKeyTyped

    private void txtColorPeloKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtColorPeloKeyTyped
        int key = evt.getKeyChar();

        boolean mayusculas = key >= 65 && key <= 90;
        boolean minusculas = key >= 97 && key <= 122;
        boolean espacio = key == 32;

        if (!(minusculas || mayusculas)) {
            evt.consume();
        }

        if (txtColorPelo.getText().trim().length() == 15) {
            evt.consume();
        }

    }//GEN-LAST:event_txtColorPeloKeyTyped

    private void txtColorOjosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtColorOjosKeyTyped
        int key = evt.getKeyChar();

        boolean mayusculas = key >= 65 && key <= 90;
        boolean minusculas = key >= 97 && key <= 122;
        boolean espacio = key == 32;

        if (!(minusculas || mayusculas)) {
            evt.consume();
        }

        if (txtColorOjos.getText().trim().length() == 15) {
            evt.consume();
        }
    }//GEN-LAST:event_txtColorOjosKeyTyped

    private void llenarTabla(ArrayList<Perfil> perfiles) {

        DefaultTableModel modelPerfil1 = (DefaultTableModel) tblPerfil1.getModel();
        DefaultTableModel modelPerfil2 = (DefaultTableModel) tblPerfil2.getModel();

        int rowCountClientes = tblPerfil1.getRowCount();

        for (int i = rowCountClientes - 1; i >= 0; i--) {
            modelPerfil1.removeRow(i);
            modelPerfil2.removeRow(i);
        }

        Object rowDataPerfiles1[] = new Object[6];
        Object rowDataPerfiles2[] = new Object[5];
        if (perfiles != null) {
            for (int i = 0; i < perfiles.size(); i++) {

                rowDataPerfiles1[0] = perfiles.get(i).getCodigo();
                rowDataPerfiles1[1] = perfiles.get(i).getEstado().toString();
                rowDataPerfiles1[2] = perfiles.get(i).getSexo().toString();
                rowDataPerfiles1[3] = perfiles.get(i).getAlturaMin();
                rowDataPerfiles1[4] = perfiles.get(i).getAlturaMax();
                rowDataPerfiles1[5] = perfiles.get(i).getEdadMin();

                modelPerfil1.addRow(rowDataPerfiles1);
            }

            for (int i = 0; i < perfiles.size(); i++) {
                rowDataPerfiles2[0] = perfiles.get(i).getEdadMax();
                rowDataPerfiles2[1] = perfiles.get(i).getColorCabello();
                rowDataPerfiles2[2] = perfiles.get(i).getColorOjos();
                rowDataPerfiles2[3] = perfiles.get(i).getTipoPerfil().toString();
                rowDataPerfiles2[4] = perfiles.get(i).isExperiencia();

                modelPerfil2.addRow(rowDataPerfiles2);
            }
        }
    }

    public ArrayList<Perfil> getPerfil() {
        return perfiles;
    }

    public Sexo toSexo(String s) {
        Sexo sexo = null;
        switch (s) {
            case "Masculino":
                sexo = Sexo.MASCULINO;
                break;
            case "Femenino":
                sexo = Sexo.FEMENINO;
                break;
        }
        return sexo;
    }

    public EPerfil toPerfil(String p) {
        EPerfil perfil = null;
        switch (p) {
            case "Actor":
                perfil = EPerfil.Actor;
                break;
            case "Modelo":
                perfil = EPerfil.Modelo;
                break;
        }
        return perfil;
    }

    public Estado toEnum(String e) {
        Estado estado = null;
        switch (e) {
            case "Aguascalientes":
                estado = Estado.Aguascalientes;
                break;
            case "Baja California":
                estado = Estado.BajaCalifornia;
                break;
            case "Baja California Sur":
                estado = Estado.BajaCaliforniaSur;
                break;
            case "Campeche":
                estado = Estado.Campeche;
                break;
            case "Coahuila":
                estado = Estado.Coahuila;
                break;
            case "Colima":
                estado = Estado.Colima;
                break;
            case "Chiapas":
                estado = Estado.Chiapas;
                break;
            case "Chihuahua":
                estado = Estado.Chihuahua;
                break;
            case "Durango":
                estado = Estado.Durango;
                break;
            case "CDMX":
                estado = Estado.CDMX;
                break;
            case "Guanajuato":
                estado = estado.Guanajuato;
                break;
            case "Guerrero":
                estado = Estado.Guerrero;
            case "Hidalgo":
                estado = Estado.Hidalgo;
                break;
            case "Jalisco":
                estado = Estado.Jalisco;
                break;
            case "Michoacán":
                estado = Estado.Michoacán;
                break;
            case "Morelos":
                estado = Estado.Morelos;
                break;
            case "Nayarit":
                estado = Estado.Nayarit;
                break;
            case "Nuevo León":
                estado = Estado.NuevoLeón;
                break;
            case "Oaxaca":
                estado = Estado.Oaxaca;
                break;
            case "Puebla":
                estado = Estado.Puebla;
                break;
            case "Querétaro":
                estado = Estado.Querétaro;
                break;
            case "Quintana Roo":
                estado = Estado.QuintanaRoo;
                break;
            case "San Luis Potosí":
                estado = Estado.SanLuisPotosí;
                break;
            case "Sinaloa":
                estado = Estado.Sinaloa;
                break;
            case "Sonora":
                estado = Estado.Sonora;
                break;
            case "Tabasco":
                estado = Estado.Tabasco;
                break;
            case "Tamaulipas":
                estado = Estado.Tamaulipas;
                break;
            case "Tlaxcala":
                estado = Estado.Tlaxcala;
                break;
            case "Veracruz":
                estado = Estado.Veracruz;
                break;
            case "Yucatán":
                estado = Estado.Yucatán;
                break;
            case "Zacatecas":
                estado = Estado.Zacatecas;
                break;
        }

        return estado;
    }

    public void limpiar() {
        txtCodigo.setText("");
        comboBoxEstados.setSelectedIndex(0);
        comboBoxSexo.setSelectedIndex(0);
        txtAlturaMin.setText("");
        txtAlturaMax.setText("");
        txtEdadMin.setText("");
        txtEdadMax.setText("");
        txtColorPelo.setText("");
        txtColorOjos.setText("");
        comboBoxPerfil.setSelectedIndex(0);
        comboBoxExperiencia.setSelectedIndex(0);
    }

    public boolean validar() {
        if (txtAlturaMax.getText().equals("") || txtAlturaMin.getText().equals("") || txtCodigo.getText().equals("")
                || txtColorOjos.getText().equals("") || txtColorPelo.getText().equals("") || txtEdadMax.getText().equals("")
                || txtEdadMin.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Llene todos los campos requeridos!");
            return false;
        }
        float alturaMin = 0;
        float alturaMax = 0;
        int edadMin = 0;
        int edadMax = 0;
        try {
            alturaMin = Float.parseFloat(txtAlturaMin.getText());
            alturaMax = Float.parseFloat(txtAlturaMax.getText());
            edadMin = Integer.parseInt(txtEdadMin.getText());
            edadMax = Integer.parseInt(txtEdadMax.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Ingrese los debidos formatos!");
            return false;
        }

        if (alturaMin > alturaMax || alturaMin <= 0 || alturaMax > 260 || alturaMax <= 0) {
            JOptionPane.showMessageDialog(null, "Ingresar alturas validas!, llenela para guardar.");
            return false;
        }

        if (edadMin > edadMax || edadMin <= 0 || edadMax > 120 || edadMax <= 0) {
            JOptionPane.showMessageDialog(null, "Ingresar edades validas!, llenela para guardar.");
            return false;
        }

        return true;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnInsertar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JComboBox<String> comboBoxEstados;
    private javax.swing.JComboBox<String> comboBoxExperiencia;
    private javax.swing.JComboBox<String> comboBoxPerfil;
    private javax.swing.JComboBox<String> comboBoxSexo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblPerfil1;
    private javax.swing.JTable tblPerfil2;
    private javax.swing.JTextField txtAlturaMax;
    private javax.swing.JTextField txtAlturaMin;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtColorOjos;
    private javax.swing.JTextField txtColorPelo;
    private javax.swing.JTextField txtEdadMax;
    private javax.swing.JTextField txtEdadMin;
    // End of variables declaration//GEN-END:variables
}
